apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilorin-watch-deployment
  labels:
    app: ilorin-watch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ilorin-watch
  template:
    metadata:
      labels:
        app: ilorin-watch
    spec:
      containers:
      - name: ilorin-app
        # This is a placeholder. The CI/CD pipeline will replace "LATEST" 
        # with the actual commit hash automatically.
        image: us-central1-docker.pkg.dev/aminalawal/ilorin-app-repo/app:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"