apiVersion: v1
kind: Service
metadata:
  name: ilorin-watch-service
spec:
  type: LoadBalancer # <--- POINT HERE. "This asks Google for a Public IP."
  selector:
    app: ilorin-watch
  ports:
  - protocol: TCP
    port: 80        # The outside world hits port 80
    targetPort: 80 # The container listens on 8080